# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhFollow < Formula
  desc "A GitHub CLI extension to manage your follow list from the terminal"
  homepage "https://github.com/h1s97x/gh-follow"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_darwin_amd64.tar.gz"
      sha256 "b071fa7e8fbb8d1a568494d92463ab37d5212ddd3583712ed1ede32705a199c0"

      define_method(:install) do
        bin.install "gh-follow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_darwin_arm64.tar.gz"
      sha256 "07d19c8b0d7c1e53cd97db3f4784ef6be077f9e6e18c13a514dcb2965a251a2c"

      define_method(:install) do
        bin.install "gh-follow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_linux_amd64.tar.gz"
      sha256 "224ad4a8a3dba3004c04d4d627d39a395d2f1c41b4f9571db6c8fd2aea42d22a"
      define_method(:install) do
        bin.install "gh-follow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_linux_arm64.tar.gz"
      sha256 "55481e1334db25c7675b2f480f3e5d64ddb654a4e03cb187434585ec7279d857"
      define_method(:install) do
        bin.install "gh-follow"
      end
    end
  end
end
