# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhFollow < Formula
  desc "A GitHub CLI extension to manage your follow list from the terminal"
  homepage "https://github.com/h1s97x/gh-follow"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_darwin_amd64.tar.gz"
      sha256 "2951eba9da0e0eadf3bba60c57a8e5393a07de3ec8e5301aa4fb9f4b96999fac"

      define_method(:install) do
        bin.install "gh-follow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_darwin_arm64.tar.gz"
      sha256 "2d0df310776486084e39b2ba09d814492a2d1dbb4944aaaf4c71ceae561d8330"

      define_method(:install) do
        bin.install "gh-follow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_linux_amd64.tar.gz"
      sha256 "5877f8103b8e7d70058f68cb76ff969be5bcc1e26f422ea15f3e4dfecaeb83ea"
      define_method(:install) do
        bin.install "gh-follow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_linux_arm64.tar.gz"
      sha256 "6f8a1eb21386714d7b299c91e991a28cc05132a19dc06624fddcedc564247292"
      define_method(:install) do
        bin.install "gh-follow"
      end
    end
  end
end
