# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhFollow < Formula
  desc "A GitHub CLI extension to manage your follow list from the terminal"
  homepage "https://github.com/h1s97x/gh-follow"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_darwin_amd64.tar.gz"
      sha256 "75854ce0aa6ffac530d3c7bc6636ce9489d11da1c12247fc8b56c256b8785ac1"

      define_method(:install) do
        bin.install "gh-follow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_darwin_arm64.tar.gz"
      sha256 "f264107e7d475a0f95edb13212f59dffe3d25238fb6d1997754659de9aa24276"

      define_method(:install) do
        bin.install "gh-follow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_linux_amd64.tar.gz"
      sha256 "34934401f58dc074c6b4d167fa7cb873f67bfef1b2cce6f1d7b71c6c54949bdd"
      define_method(:install) do
        bin.install "gh-follow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/h1s97x/gh-follow/releases/download/v1.0.1/gh-follow_1.0.1_linux_arm64.tar.gz"
      sha256 "95abc2c7eb6457c3cc31d8173a000b373cb19dba1149a070e095864863100618"
      define_method(:install) do
        bin.install "gh-follow"
      end
    end
  end
end
